#!/bin/bash -e
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=$(getApplication)


if [[ "$1" == "-parallel" ]]; then
    runParallel $application
    # Mesh reconstruction is not needed when a dynamic mesh is used
    # Use "Decomposed Case" in Paraview instead
else
    runApplication $application
fi

echo "All is done!"
