FROM mygetsy/openfoam-dev-ccls:2406

USER root

RUN chmod -R a+rX /usr/lib/openfoam/openfoam2406/build/linux64GccDPInt32Opt/.ccls-cache
RUN chmod -R a+rX /usr/lib/openfoam/openfoam2406/build/linux64GccDPInt32Opt/compile_commands.json


# 1. Argument for User ID (matches standard 1000, but can be overridden)
ARG USERNAME=openfoam
ARG USER_UID=123456
ARG USER_GID=$USER_UID


USER $USERNAME
